# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9TCgvX5QSSRNyHOQh-DOmIp7YDRjiXi
"""

print ("------EMPLOYEE SHEET------")
name= input("Enter The Name Of Employee :")
code= input("Enter Employee Code :")
basic= float(input("Enter the salary :"))
da= (basic*85/100)
ta=(basic*20/100)
hra=(basic*15/100)
gross = basic +da+ta+hra
pf=(gross*8.33/100)
net= (gross-pf)
print ("the da is : ",da)
print("the ta is : ",ta)
print("the hra is : ",hra)
print ("The gross salary is :",gross)
print("The pf is :",pf)
print("The net salary :",net)

